version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache
    ports:
      - "8081:80"
    volumes:
      - ./app:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - APACHE_SERVER_NAME=localhost
